version: 0.1

phases:
  build:
    commands:
      - docker build -t ml-test-repo .

  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region "us-east-1")
      - docker tag ml-test-repo:latest 965852169031.dkr.ecr.us-east-1.amazonaws.com/prabhu-ecs-test:latest
      - docker push 965852169031.dkr.ecr.us-east-1.amazonaws.com/prabhu-ecs-test:latest
